language: python
# TODO: What version of python is on the ev3s
python:
  - "3.5"

# Extra Dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python3.5-dev libboost-python-dev

# This will run all python files in any subdirectory of the test directory with
# test in their name
script: make test
