language: python
# TODO: What version of python is on the ev3s
python:
  - "3.5"

sudo: required
services:
  - docker

# This will run all python files in any subdirectory of the test directory with
# test in their name
script: pwd
